### ISSUE TITLE
portfolio pages

### ISSUE THREAD

**Issue by LauraWN** [ga-wdi-exercises/portfolio_pages#10]
I have an index.html file, the styles.css page, and a style.scss page, but the styles from the compiled css page aren't being applied. I'm going to have to figure out why it won't link in the morning.

http://laurawn.github.io

also available here: http://codepen.io/anon/pen/jbOLeP?editors=110

**Comment by RobertAKARobin** [comment]
Weird! We'll have time to go over that today, if you'd like.
