### ISSUE TITLE
Megan's Portfolio

### ISSUE THREAD

**Issue by megancoyle** [ga-wdi-exercises/portfolio_pages#101]
https://github.com/megancoyle/megancoyle.github.io

Comfort score: 5
Completeness: 3 (I guess we could say 5 if a prototype works? :) )

I'm pretty comfortable with CSS but I wanted to challenge myself by using SASS for this. I have yet to add any JavaScript functionality to this, but a few functionalities I'd want to add include: transitions for clicking the anchor links, some sort of tabbed browsing view for the portfolio sections (since it will include web, application, and illustration work), and sorting functionality. In general I definitely want to add some sort of templating for this so when users click a portfolio item, a pop up appears with a larger image and additional info about the piece. If you have any suggestions for something for me to look into for that, let me know!

**Comment by andrewsunglaekim** [comment]
so you want a modal! i would just google how to make a modal. CSS tricks has great articles on it as well. This looks amazing though! Great work. 👍
