### ISSUE TITLE
Chase's Portfolio page!

### ISSUE THREAD

**Issue by chaseTfreeman** [ga-wdi-exercises/portfolio_pages#107]
https://github.com/chaseTfreeman/chaseTfreeman.github.io
[Actual Page](chasetfreeman.github.io)
comfort: 1, increased to 3, by the the end of the day. Needed practice. Still need a lot more. Would like to learn more tips/tricks/bootstrap/etc. Doing CSS from scratch sucks. I also am not a very good designer/don't have good taste. Had a great original wireframe/architecture though.

completeness: ?, worked all day and then some so I think 5 for completing the assigned task even though the page is sucky.

**Comment by andrewsunglaekim** [comment]
preaching to the choir bud. But that's alright! I'm so glad that your comfort increased over the course of the lab day, that's what lab days are for! I wouldn't be too concerned this was just to get your feet wet and get comfortable writing HTML and CSS 👍
