### ISSUE TITLE
pamelas hw

### ISSUE THREAD

**Issue by pamelaolney** [ga-wdi-exercises/portfolio_pages#108]
git@github.com:pamelaolney/pamelaolney.github.io.git

https://pamelaolney.github.io/

comfort: 4
completeness: 5

This was okay. I figure once I learn more about javascript that I will be able to add more to my site.

**Comment by superbuggy** [comment]
Like I said Thursday, this looks good. I would increase the size of the navbar at the bottom, considering prospective employers and recruiters viewing this on mobile. That's really my only feedback. You can preview Mobile Mode in the inspector in Chrome for reference. Good work!
