### ISSUE TITLE
Taylor's portfolio (6/30 lab)

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/portfolio_pages#109]
Published page: https://tedwards1884.github.io/portfolio/
Personal repo: https://github.com/tedwards1884/portfolio

Completeness: 4 (obviously there's still a lot of work to do, but relative to what I feel like I could do at this point in the course I'd say 4/5)
Comfort: 3.5-4

Comments: It feels good to be mastering a lot of small skills and being able to incorporate them, and Bootstrap has proven satisfying once I wrangled it into place. I was able to only get a very little bit of styling done - getting the content to be as responsive as I want is going to be a challenge, but I feel equipped to go up against it. Still having trouble getting my head around GH-pages and what's is supposed to do... I think I will do some investigation and simulating over the next few days, but with guidance from others I have at least been able to get a current version published. Looking forward to  tweaking and improving this portfolio - I have some exciting ideas for this, and can't wait to gain the skills to implement them.

**Comment by andrewsunglaekim** [comment]
:+1: awesome man! let me know if you have any questions about gh-pages.
