### ISSUE TITLE
https://github.com/AHStudyBank/ahstudybank.github.io.git

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/portfolio_pages#114]
Updated.

comfort: 3

completeness: 3

**Comment by superbuggy** [comment]
Solid start, Alex. The only issue that I'd point out is that the buttons kind of spazz out during mouse-overs.  Other than that, I might give some thought to how it will look on a mobile device. Tweaking the layout to feel more vertical might be to your advantage here. Prospective employers and recruiters in particular might be looking at your portfolio on mobile.

You can preview mobile mode in the inspector (highlighted in blue in the image below):

![image](https://cloud.githubusercontent.com/assets/17716232/16572410/4426e57c-4236-11e6-8a5e-560617791e3c.png)
