### ISSUE TITLE
Ben Brizzi portfolio

### ISSUE THREAD

**Issue by brizzi10** [ga-wdi-exercises/portfolio_pages#116]
https://github.com/brizzi10/brizzi10.github.io

comfort: 4
completeness: 2

I am definitely comfortable about accomplishing the goals that I set out for with the assignment: using the grid structure from the craigslist example and getting the z axis javascript to work.

The fonts and colors are certainly not the most visually scintillating, but since those were not really what I spent my time on I definitely feel comfortable about upgrading them as my skill increases. In terms of a portfolio page this is certainly not complete by any means, but it felt like the lab accomplished exactly what you had advised: learn by making mistakes and solving my own problems.

**Comment by andrewsunglaekim** [comment]
:+1:
