### ISSUE TITLE
Bootstrap & Sass Submission

### ISSUE THREAD

**Issue by karldonus** [ga-wdi-exercises/portfolio_pages#12]
https://github.com/karldonus/karldonusdotcom

Completeness: 2
Comfort Level: 4

Observations: Still have a long, long ways to go. It isn't so much that it is technically challenging, it just feels like herding cats. I know the grid system in principle. I can implement it by itself. However, when I start adding other styling elements, it begins to rebel. I've come to appreciate putting the grid in FIRST, then putting the content in (rather than the other way around, which I spent most of my time trying to undue). Also, I spent way too much time trying to make the color scheme work. That's the nice thing with variables, I can easily switch these themes out much more easily.

**Comment by RobertAKARobin** [comment]
Hah, yeah, that's CSS. The physical layout is always the trickiest thing, and so that's what you should start with. The color scheme usually doesn't inform the physical layout, and it's easy-peasy to change.
