### ISSUE TITLE
Rasheeda Alexander's Portfolio

### ISSUE THREAD

**Issue by RasheedaAlexander** [ga-wdi-exercises/portfolio_pages#121]
https://github.com/RasheedaAlexander/rasheedaalexander.github.io

Comfort: 5
Completeness: 2

I'm not sure exactly where I'd like to go with this site, yet. But I'm working towards a minimalistic theme and hope to create a blog page as well. For the portfolio work, I'd like to give a scroll feature a try so that everything isn't on the page at once (maybe).

**Comment by andrewsunglaekim** [comment]
:+1:
