### ISSUE TITLE
Daniela Noir Portfolio HW

### ISSUE THREAD

**Issue by danielanoir** [ga-wdi-exercises/portfolio_pages#122]
comfort: 4
completeness: 5

comment: I'm not comfortable with everything I was trying to do (specifically flex). 

http://github.com/danielanoir/danielanoir.github.io

**Comment by superbuggy** [comment]
Your code and layout look good. Flex takes a bit of getting used to, but I would say to keep experimenting. It may help you decide how you'd like to optimize for mobile as well. Potential employers and recruiters will quite possibly be viewing your portfolio on their mobile devices. Your design looks pretty decent on mobile view, though some of the menu text might appear tiny on an iPhone 5. Just food for thought. Good work!
