### ISSUE TITLE
Winston HW

### ISSUE THREAD

**Issue by zorba-strange** [ga-wdi-exercises/portfolio_pages#124]
comfort: 4
completeness: mother fucking 5

https://github.com/zorba-strange/zorba-strange.github.io/tree/master

**Comment by superbuggy** [comment]
The layout is really strong; this looks exactly how I'd expect a designer's website to look. Doesn't look like there is much unnecessary code, so good job there as well. 

As far as next steps, you might consider making your nav links react to hovers in some fashion. Another idea to consider might be making the links into jump-links, so it would have a vertical scrolling format that would look good on mobile. That's just a thought though; you could probably manage something more original than the vertical scrolling website/blog pattern, which is pretty ubiquitous right now. 👍 👍 👍
