### ISSUE TITLE
Andres Espinoza's Portfolio

### ISSUE THREAD

**Issue by a-espinoza** [ga-wdi-exercises/portfolio_pages#125]
Link to my repo:

https://github.com/a-espinoza/a-espinoza.github.io

**Andres E.**

**Comment by amaseda** [comment]
Solid start. Encourage you to add some content beyond the header so you can experiment with laying out an entire page. 

What are your thoughts on how you can space elements in your header out so they're not on top of each other?

Cool that you played around with animations!

Let me know if you have any questions!
