### ISSUE TITLE
Sass and Bootstrap

### ISSUE THREAD

**Issue by jsm13** [ga-wdi-exercises/portfolio_pages#13]
https://github.com/jmas13/jmas13.github.io
Comfort: 4
Completeness: 2
Specific Issue: 
https://github.com/jmas13/jmas13.github.io/blob/master/.gitignore#L1-L2
Did not put as much time into this as I would have liked to but will definitely continue. One of the things that confused be a little bit was what I should have git ignoring. Using bower to install dependencies I wound up with tons of supporting files I don't think I need but want to keep around for reference. I put .sass-cache and bower_components in my .gitignore and then moved specific files needed for rendering the page in my assets file but am not sure if this was correct to do.

**Comment by RobertAKARobin** [comment]
We didn't really talk about that. Absolutely put `bower_components` in your gitignore! It's literally the same thing as `node_modules`.
