### ISSUE TITLE
Barrett Cope's Portfolio Page

### ISSUE THREAD

**Issue by bcope** [ga-wdi-exercises/portfolio_pages#132]
https://github.com/bcope/bcope.github.io
completeness: 4 -- had to give up on my new portfolio site in order to submit hw on time. I will update this repo with the site I worked on today when it is ready to deploy.
confidence: 2 -- had trouble setting up a custom domain. I did it but there was unexpected behavior. I read the documentation but it wasn't super helpful.

**Comment by amaseda** [comment]
:+1: Awesome theme! Let me know if you have any questions about anything in particular you did here.
