### ISSUE TITLE
Mike Rubin Portfolio Page

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/portfolio_pages#134]
https://github.com/merubin/merubin.github.io
completeness: 3 -- I have issues with my flexbox spacing on the nav side ( left) and issues with wrapping the project boxes in pairs of twos on the (right side) I also want the nave side not scroll and the projects side to scroll, but if I used fixed the projects side goes under the nav side so I undid this.

confidence: 2 -- Still need to work on flex box.  Will work this weekend on completing airbnb exercise.

**Comment by jshawl** [comment]
@merubin `<img src="img/nav/seperator.png">` needs to be `max-width:100%`

From there, display:flex has some interesting consequences. Let me know if you'd like to pair on this one!

:+1:
