### ISSUE TITLE
Portfolio (Liza Floyd)

### ISSUE THREAD

**Issue by lizafloyd** [ga-wdi-exercises/portfolio_pages#146]
JS not working.  CV and About links working.

https://github.com/lizafloyd/lizafloyd.github.io

Comfort_level: 5
Completeness: 4.5

**Comment by amaseda** [comment]
The CSS doesn't seem to be loading when I visit https://lizafloyd.github.io/. Probably because you're referencing the absolute local path to your stylesheet [here](https://github.com/lizafloyd/lizafloyd.github.io/blob/master/index.html). Try relative.
