### ISSUE TITLE
(Latoya) Portfolio

### ISSUE THREAD

**Issue by LWatsonlm** [ga-wdi-exercises/portfolio_pages#148]
https://github.com/LWatsonlm/LWatsonlm.github.io

**Comment by LWatsonlm** [comment]
Comfort: 4
Completeness: 5
Everything works, I had some discomfort with git and with my nav bar not clearing the body

**Comment by jshawl** [comment]
👍 Looks great!

**Comment by jshawl** [comment]
Friendly reminder to use relative paths - ![](https://dl.dropbox.com/s/570wft6k2x9e1d1/Screenshot%202016-09-12%2015.42.48.png?dl=0)
