### ISSUE TITLE
Jared Edwards

### ISSUE THREAD

**Issue by jarededwards** [ga-wdi-exercises/portfolio_pages#173]
Link to repo-- 
https://github.com/JaredEdwards/JaredEdwards.github.io/commits/master

**Comment by nayana487** [comment]
where you having issues? don't see much here beyond a short html file

**Comment by jarededwards** [comment]
No, I thought we just needed to set up the GitHub pages for the lab and have our files in place. Thats why I asked my question during squad scrum about what level we needed for credit. I misunderstood the response about it being a (very important) work throughout the entirety of the course not just having a simple site for that day.
