### ISSUE TITLE
Casey_Solution

### ISSUE THREAD

**Issue by caseyagil** [ga-wdi-exercises/portfolio_pages#18]
Attached is my link to the github.io
https://github.com/caseyagil/caseyagil.github.io

I worked with Charles Whang.

**Comment by beckybeauchamp1** [comment]
Hi Casey,

Good morning! I made a PR to your repo and added comments throughout your code. The link to the PR is here: https://github.com/caseyagil/caseyagil.github.io/pull/2

I think that your page is a good starting point! Most of the feedback is directly related to best practices, and making sure we are using html elements and adding classes that are semantic. As far as your jQuery, let's hold off on refactoring until were on that unit. For this week, I would encourage you to go back and try to add Vanilla JS instead and see if you can get the functionality working. If you have any further questions, please let me know!
