### ISSUE TITLE
Portfolio Lab - Ben Shapiro

### ISSUE THREAD

**Issue by pretorben** [ga-wdi-exercises/portfolio_pages#184]
https://github.com/pretorben/pretorben.github.io

Completeness: 1
Comfort Level: 3

I want to fix how my main body text is displayed and get my picture to stay centered in relative position to the text.

**Comment by superbuggy** [comment]
The solution might to have the image take up the 100% of the height of the container, but then set a max-height on the container, so your picture doesn't stretched out too much (if someone had a huge screen and set the browser window to the entire huge screen, for example).
