### ISSUE TITLE
CLI HW "Portfolio Pages" (Justin Shin)

### ISSUE THREAD

**Issue by Justin-Shin** [ga-wdi-exercises/portfolio_pages#187]
https://justin-shin.github.io/

**Comment by Justin-Shin** [comment]
Comfort: 3
Completion: -1

I feel relatively comfortable doing this stuff, but I also am having difficulty creating something out of nothing.  Assignments are easier when I have an end goal, but I don't have one here.  It makes the going much slower.  I suspect my final product will look nothing like this does.

I put completeness at -1 for this reason, and I put comfort at 3 because I think I can get it to do what I need it to do, but I don't feel comfortable making something quality.  Hopefully this changes soon.

**Comment by superbuggy** [comment]
Yeah you're in kind of a position with this assignment where you are kind of banking on future skills. I too am the kind of person who prefers structure when I am learning something new. In situations where I am starting from scratch, I kind of throw spaghetti at the wall, but I try to do it noodle by noodle. Other times, I have to sit down with a few sheets of scratch paper to figure what noodle to throw first. I might jot down a few pieces of content, then try to organize them by category, and then create a nav-bar from those categories, for example.
