### ISSUE TITLE
Lisa Burr Profile Page

### ISSUE THREAD

**Issue by laburr27** [ga-wdi-exercises/portfolio_pages#188]
confidence: 2
completeness: 2

https://github.com/laburr27/laburr27.github.io

My brain is too fried for creativity this afternoon so I did a lot of basic formatting and playing with fonts; emulating code presented in class lessons.

I am probably going to wind up rewriting and editing the code as we go along.  Right now I'm just getting the dynamics down

**Comment by superbuggy** [comment]
Good start! I like how you've structured your html!
