### ISSUE TITLE
Portfolio Aaron Andrews

### ISSUE THREAD

**Issue by andrews94** [ga-wdi-exercises/portfolio_pages#189]
https://github.com/andrews94/portfolio

**Comment by superbuggy** [comment]
nice work although part of the assignment was to [deploy to github pages](https://pages.github.com/).

once you have the repo set up (in your case `andrews94.github.io`), you can create a `gh-pages`
branch on this repo `portfolio` and then access your deployed site at `andrews94.github.io/portfolio`
