### ISSUE TITLE
charleshwang_solution

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/portfolio_pages#19]
charlesthwang.github.io

collaborated with casey gil

comfort: 3/5
completeness: 5/5

**Comment by beckybeauchamp1** [comment]
Hi Charles, 

Good morning, hope you had a nice weekend! Good job on your portfolio, I think that is a good starting point! I would encourage you to continue working on it and expand on it further. I opened a PR and made additional comments inline: https://github.com/charlesthwang/charlesthwang.github.io/compare/master...beckybeauchamp1:beckys-comments?expand=1

If you have any more questions, please let me know!
