### ISSUE TITLE
Portfolio by Habtamu Abere

### ISSUE THREAD

**Issue by HabRonan** [ga-wdi-exercises/portfolio_pages#204]
https://github.com/HabRonan/HabRonan.github.io

https://habronan.github.io

I apologize in advance for the damage to your eyes!

**Comment by amaseda** [comment]
:+1: AH MY EYES! Just kidding -- good start! With some CSS practice this will look better.

From a code cleanliness perspective, I would recommend...
* Proper code indentation
* CSS class naming consistency (e.g., making all classes lower-case)

These are the kind of things that potential employers will be looking out for!
