### ISSUE TITLE
Portfolio Page (Meag Doherty)

### ISSUE THREAD

**Issue by meagdoh** [ga-wdi-exercises/portfolio_pages#219]
https://github.com/meagdoh/meagdoh.github.io

Comfort score, out of 3
Completeness score, out of 3

The good news is I have a well-defined mockup for the site: https://docs.google.com/drawings/d/10vIqqna1OmsduFmDzaxPBx35DkZAj-usYFWG4v862xI/edit

Still struggling with flex-box and ordering elements accordingly.

**Comment by jsm13** [comment]
👍 wireframe is great. We'll get plenty of practice with CSS / HTML so should be quick to implement the rest of this when you get back to it
