### ISSUE TITLE
http://github.com/aeaghannam/aeaghannam.github.io

### ISSUE THREAD

**Issue by aeaghannam** [ga-wdi-exercises/portfolio_pages#230]
http://github.com/wdidcstudent/wdidcstudent.github.io

**Comment by aeaghannam** [comment]
https://github.com/aeaghannam/aeaghannam.github.io/commit/655a823b39a328cbb77cd462290540e6a001eeb4

**Comment by aeaghannam** [comment]
https://github.com/aeaghannam/aeaghannam.github.io/commit/655a823b39a328cbb77cd462290540e6a001eeb4

**Comment by aeaghannam** [comment]
https://github.com/aeaghannam/aeaghannam.github.io/commit/655a823b39a328cbb77cd462290540e6a001eeb4

**Comment by jsm13** [comment]
👍
