### ISSUE TITLE
Christine Movius About Me Page

### ISSUE THREAD

**Issue by christine-sm** [ga-wdi-exercises/portfolio_pages#24]
https://github.com/cmmovius/cmmovius.github.io

Comfort: 4
Completion: 4

This is a good start, but I know there are many complex CSS and JS functions that I don't know.

**Comment by christine-sm** [comment]
My next steps involve taking what I learned in Dash/learning more to make this page responsive.

**Comment by beckybeauchamp1** [comment]
Hi Christine, 

Good afternoon! I just submitted a PR to your portfolio repo. Please see my additional inline comments here: https://github.com/cmmovius/cmmovius.github.io/pull/3

I think your portfolio looks great! You definitely are off to an awesome start. I couldn't really find much else to offer as suggestions. Let me know if you have any questions!
