### ISSUE TITLE
Rough Draft of Portfolio

### ISSUE THREAD

**Issue by mitcheguevara** [ga-wdi-exercises/portfolio_pages#245]
[Link to page](https://mitcheguevara.github.io/portfolio/)
- I need to add an about me section
-The content on the page is mainly sections I would like to have
-The font sizing is off
-I need to clean it up and adjust the nav
-I need to re wire the page

**Comment by jsm13** [comment]
Be sure to include scores for **comfort/confidence** and **completion** on all submissions (and optionally any questions you have that I can help with).

Looks good!
