### ISSUE TITLE
Brittany Branson's Portfolio Page

### ISSUE THREAD

**Issue by Dibbledl01** [ga-wdi-exercises/portfolio_pages#25]
My partner was Anissa Jones!

Below is a link to my repo. I had created a new one for this portfolio page.

[https://github.com/Dibbledl01/my-portfolio-page.git](url)

**Comment by Dibbledl01** [comment]
The above link appears to give an error message. Maybe try this? https://github.com/Dibbledl01/my-portfolio-page.git

**Comment by beckybeauchamp1** [comment]
Hi Brittany,

Good afternoon, hope you have had a great weekend! Good job on your portfolio, I think that this is a nice starting point! I really like the look and design of your portfolio, and thinks it conveys your personality well :+1: 

I made a PR with additional comments for your code. A couple of suggestions. One, just be aware that your html did not validate, make sure that you run it through a validator! Additionally, please refer to my inline comments about your jQuery. I would encourage you to go back this week and try to add in additional functionality using Vanilla JS instead. 

Please let me know if you have any more questions!
