### ISSUE TITLE
Colleen Portfolio

### ISSUE THREAD

**Issue by colleeno** [ga-wdi-exercises/portfolio_pages#259]
https://github.com/colleeno/colleeno.github.io

confidence: 4
completion: 1

ROUGH Wireframe

**Comment by jsm13** [comment]
Looks great! 

I'm reading confidence and completion as 5 being totally confident and complete. If that's the case I'd rank completion much higher.

As a note, if you have any specific questions I can investigate, you can leave those questions in the PR message as well
