### ISSUE TITLE
Hyojin Sarchet's Portfolio

### ISSUE THREAD

**Issue by hyojinsarchet** [ga-wdi-exercises/portfolio_pages#265]
https://hyojinsarchet.github.io/

**Comment by juancgarcia** [comment]
Good Job!

Note: As per the [submission guidelines](https://github.com/ga-wdi-exercises/portfolio_pages#submission), we did want a link to [your repo](https://github.com/hyojinsarchet/hyojinsarchet.github.io), not the published webpage.
