### ISSUE TITLE
Craig Eisen's Portfolio Page

### ISSUE THREAD

**Issue by Ceisen9** [ga-wdi-exercises/portfolio_pages#28]
My partner was Brendan Magee.

Below is a link to my repo and my webpage.

https://github.com/Ceisen9/Ceisen9.github.io

http://ceisen9.github.io/

**Comment by jshawl** [comment]
:+1: excellent job on this assignment!! https://github.com/jshawl/Ceisen9.github.io/commit/dc6ba5c1e267444799b2441f0884b1cdedf90620
