### ISSUE TITLE
Keith's portfolio site

### ISSUE THREAD

**Issue by khenry10** [ga-wdi-exercises/portfolio_pages#31]
https://github.com/khenry10/khenry10.github.io

**Comment by joe-gz** [comment]
Hey Keith!

Nice start here with the portfolio page.  I've added in a bunch of comments in the css and html files. 
This link will send you to my forked repo with the comments I've included in your code:
https://github.com/joe-gz/khenry10.github.io/commit/f4129dbf9296672ed631586197f0124e580692fa

A couple things to consider:
1. I gave a couple examples of cleaning up your css code a bit.  Basically when you see a lot of repeating code, it would be really useful to go back and combine things
2. Totally feel free to ignore my suggestions about things like transitions. It's just a random styling hint!
3. it's picky, but just be careful of indenting

Let me know if you have any questions! happy to run through these during our 1-1 or any other time.

Thanks,
