### ISSUE TITLE
Caitlin's Portfolio Site

### ISSUE THREAD

**Issue by caitlindaitch** [ga-wdi-exercises/portfolio_pages#32]
Comfort: 5
Completeness: 3. Still need to add JavaScript and detail pages for all of my portfolio projects. I think the design is in a good place though!

http://caitlindaitch.github.io/portfolio/

https://github.com/caitlindaitch/portfolio

**Comment by beckybeauchamp1** [comment]
Hi Caitlin,

Good afternoon! Awesome job on your portfolio page! I added a PR to your rep with additional comments. Here is the link: https://github.com/caitlindaitch/portfolio/pull/4

To be honest, I couldn't find a ton of additional suggestions. I think you did a great job implementing bootstrap and I love the look and design of your page. You will have plenty of time to add in JS and more functionality, but this is a great start!

Please let me know if you have any more questions!
