### ISSUE TITLE
Jeffrey Eaton's portfolio page

### ISSUE THREAD

**Issue by jeffreyeaton76** [ga-wdi-exercises/portfolio_pages#34]
http://jeffreyeaton76.github.io/

**Comment by jeffreyeaton76** [comment]
FYI, I'm going to make a new site over the long weekend. For feedback on this I'd be interested to know any ways my code violates coding conventions. Somewhat separately, I'm pretty sure my vanilla JavaScript (at the bottom of index.html) violates the DRY principle.

**Comment by joe-gz** [comment]
Great start here Jeff!
A couple suggestions; mostly also in the notes i provided in the following commit: https://github.com/joe-gz/jeffreyeaton76.github.io/commit/27f9d6139a8769a81489b8cdbab90187ad44541d

In terms of "violations" I wouldn't say there is anything major.  One thing i noticed in your HTML is the use of "p" tags as wrappers. Those should only contain text, not additional html tags like ul's.

For your javascript, I agree there is some room to make it DRY! You should also consider separating it into a js file, like I did in my version.  I also started the process to "dry" it up be removing a couple variables out of the functions. Let me know if you have any questions! Happy to run through it more during 1-1 too
