### ISSUE TITLE
Farishta's Portfolio Page

### ISSUE THREAD

**Issue by LaFrish** [ga-wdi-exercises/portfolio_pages#35]
Git Repo: https://github.com/LaFrish/Farishta-Portfolio
Gitpage: http://lafrish.github.io/

**Comment by LaFrish** [comment]
The gitpage link was incorrect. The correct one is: http://lafrish.github.io/Farishta-Portfolio/ 

However, I still need to customize the page with my codes, add my purchase domain.

**Comment by jshawl** [comment]
This repository https://github.com/LaFrish/Farishta-Portfolio is the same code you sent for your WDI admissions assignment. My feedback on that is here - https://gitlab.com/jshawl/fh/commit/6fb0a5fa6ce622fd3d04b74abe8bd310d9991c8a.

Also, http://lafrish.github.io/Farishta-Portfolio/ this is a template generated by github pages.
