### ISSUE TITLE
Lab submission

### ISSUE THREAD

**Issue by jblakeman** [ga-wdi-exercises/portfolio_pages#36]
[jblakeman.github.io](http://jblakeman.github.io)

**Comment by joe-gz** [comment]
Great start here John!
I've added in a few comments to the commit linked below.  The main note i had was to avoid using negative margins. You can add margins to the elements around something to avoid doing that!

Also, just remember to add in a comfort and completeness level for all assignments. And, if there are any specific things you want commented on, feel free to leave that in here as well!

https://github.com/joe-gz/jblakeman.github.io/commit/15310de5ae98bf03624bc0461627f33466c2cc42

**Comment by jblakeman** [comment]
Thanks for the comment Joe!  I'll definitely avoid using negative margins in the future.  I'd say my comfort level with CSS is maybe 3.  Conceptually, I get it, I just need more experience playing around with/researching more about all the conventions and styling methods before I really feel comfortable.
