### ISSUE TITLE
Sanjaya's Portfolio Page: http://ssatyal.github.io/

### ISSUE THREAD

**Issue by ssatyal** [ga-wdi-exercises/portfolio_pages#38]
http://ssatyal.github.io/

comfort: 3
completeness: 5; added JS mute/enable audio buttons on the party page.

My issue right now is that there is a ton of blank space around my image. That part doesn't look very pleasing from a design perspective although it was part of my original idea for the page. In the future I may reorder my image to the top of the page and create a background cover image with the navigation bar underneath.

I had fun working on the party mode!

https://github.com/ssatyal/ssatyal.github.io

**Comment by RobertAKARobin** [comment]
Could you float it to the left of your About Me text, like in Wendy Bite?

**Comment by RobertAKARobin** [comment]
You can see my comments here:

https://github.com/ssatyal/ssatyal.github.io/pull/1/files
