### ISSUE TITLE
Matthew Portfolio

### ISSUE THREAD

**Issue by mkernsNCR** [ga-wdi-exercises/portfolio_pages#40]
Comfort level: 3
Completeness: 5

I would like some feedback as to how I can start incorporating some SASS.

My website: http://mkernsncr.github.io/Udacity-Project-1

**Comment by mattscilipoti** [comment]
:+1:
We were looking for a webpage about you, which includes links to projects you have worked on.  This looks like something you have been working on, prior to WDI.

You will have some classes about Sass throughout WDI.  If you still have some questions then, I'll be happy to help.
