### ISSUE TITLE
Patrick's Portfolio Page

### ISSUE THREAD

**Issue by pkmoran** [ga-wdi-exercises/portfolio_pages#42]
[My site](https://pkmoran.github.io)

comfort_level: 3.5
completeness: 4

I finally got the JS to work and I like the icons in the top left, but none of the content is filled out yet. Also, I couldn't quite figure out how to get the footer to stick to the bottom and the page looks awful if the window shrinks at all. So, as I continue to work on it those will be the first things to take care of.

**Comment by nolds9** [comment]
:+1:  Please review feedback in my open [pr](https://github.com/pkmoran/pkmoran.github.io/pull/2)
