### ISSUE TITLE
Kim's Portfolio Page

### ISSUE THREAD

**Issue by kimcabb** [ga-wdi-exercises/portfolio_pages#44]
http://kimcabb.github.io

Comfort: 3ish
Completeness: 3 (this version needs content)

What I posted above has a few font and color tweaks that are different from the assignment page I did as an admissions exercise.  I wanted to test out how they would look together.  I drew out a picture of how I would like my professional page to actually look, and that is a completely different entity.  But what I tested on this page this morning and discussed during the pair-up exercise this afternoon has given me a good place to start.

**Comment by mattscilipoti** [comment]
:+1: Complete
