### ISSUE TITLE
Another one - CamLatimer Portfolio

### ISSUE THREAD

**Issue by CamLatimer** [ga-wdi-exercises/portfolio_pages#48]
comfort: 4
completeness: 5
Here's my portfolio page.  Contains hidden links w/ CSS3 transitions that you find by hovering over the img in the middle of the page.  The actual content (info, linked pages, etc) is on the way.

[https://camlatimer.github.io/](url)

**Comment by beckybeauchamp1** [comment]
Hi Cam,

Good Afternoon! Great job on your portfolio page! I think the correct url is http://camlatimer.github.io/ . 
I really like the design and look of your page. I think its really unique and this is off to a good start! I would encourage you to keep adding on and expanding on it. 

I added additional comments inline through my PR. Here is the link: https://github.com/CamLatimer/CamLatimer.github.io/pull/1

Please let me know if you have any questions :+1:
