### ISSUE TITLE
vijay portfolio

### ISSUE THREAD

**Issue by vbajwa** [ga-wdi-exercises/portfolio_pages#50]
https://github.com/vbajwa/vbajwa.github.io

**Comment by RobertAKARobin** [comment]
Looking good so far, Vijay! Instead of your "contactInfo" class, how about using `<nav>` or `<address>`?

**Comment by vbajwa** [comment]
That is actually the plan robin! Was reviewing html and css and realized that would be a simple solution. Think i was biting off a  little more than i could chew to begin with. 

V
