### ISSUE TITLE
Rob's Blog

### ISSUE THREAD

**Issue by Robizzy27** [ga-wdi-exercises/portfolio_pages#52]
http://robizzy27.github.io/Index.html
http://robizzy27.github.io/test.html

**Comment by Robizzy27** [comment]
test.html is really the version I'm currently working on. Currently working on adding a nav bar and an enclosed with independent responsive resizing to house separate blogs on the same page. (If that makes any sense.) Will be making more edits to it over the weekend.

**Comment by nolds9** [comment]
:+1: Please see feedback in my open [pr](https://github.com/Robizzy27/Robizzy27.github.io/pull/2)
