### ISSUE TITLE
Kaira Johnson Portfolio

### ISSUE THREAD

**Issue by kairajohnson** [ga-wdi-exercises/portfolio_pages#58]
Comfort: 4
Completeness: 5 (for now)

kairajohnson.github.io

I had problems pushing my file because I created the files locally and didn't push the correct way

**Comment by kairajohnson** [comment]
I sent an issue (so I thought) after Jessie helped me solve my problem with sending a file in first class friday. Received a message on slack and saw that my issue wasn't sent

**Comment by joe-gz** [comment]
This is a great start Kaira. Please make sure to run your html through the validator. There are a few errors that you could clean up really quickly if you do so.  
I would also recommend checking your indentation in the html again, and try to order your css code to be a little more readable.  I added in comments to the files in the below commit:

https://github.com/joe-gz/kairajohnson.github.io/commit/2076d5d9f13c3bc52214043b9d185bcc93c857fb
