### ISSUE TITLE
Leigh's site

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/portfolio_pages#6]
http://leighvarley.github.io/
https://github.com/leighvarley/leighvarley.github.io

I've got a long way to go on this, but it was really nice to get to work on it as a homework assignment.

Comfort: 4 (based on what I've done so far)
Completeness: 2

**Comment by RobertAKARobin** [comment]
Cool font! This is off to a great start -- I love minimalist sites, and it's very "in" right now.
