### ISSUE TITLE
Mary portfolio page

### ISSUE THREAD

**Issue by marygriffus** [ga-wdi-exercises/portfolio_pages#62]
https://github.com/marygriffus/marygriffus.github.io

comfort: 4
completeness: never

Changes from admission website: took out bootstrap, took out javascript. If anyone has tips for making it prettier on small devices (or in general!), please share. :)

**Comment by tylercrosse** [comment]
Solid work I really like what you have so far! I'm happy to help with some design tips or suggestions on making the design 'responsive' (we will also formally cover responsive design later in the course). This would be a great thing that we could discuss during a 1-on-1.
