### ISSUE TITLE
Martin's Page

### ISSUE THREAD

**Issue by 7ruth** [ga-wdi-exercises/portfolio_pages#63]
Link to repository: https://github.com/7ruth/7ruth
Link to the website: martintersk.in

(I already was hosting my personal website and have a domain name, thus I didn't end up using github pages)

**Comment by andrewsunglaekim** [comment]
This looks rad! :+1: I would encourage you to start thinking about how your going to layout future projects for your portfolio on your website.

**Comment by 7ruth** [comment]
Did you see the sparkle? (and click on it).... I want to make it more prominent later as I build up a portfolio of things I am proud of and put it behind that sparkle (which will be on top of the mountain (symbolizing the uphill battle : ))
