### ISSUE TITLE
Jordan's Online Portfolio

### ISSUE THREAD

**Issue by jball23** [ga-wdi-exercises/portfolio_pages#66]
https://github.com/jball23/jball23.github.io

**Comment by jball23** [comment]
Completeness: 5
Comfort: 4

**Comment by jball23** [comment]
and by '5' I mean did the homework assignment...but the site isn't finished by any stretch. :+1:

**Comment by adambray** [comment]
https://github.com/jball23/jball23.github.io/blob/60b7ce1a35e4430bdcf90cc4e391f54f3f59f315/index.html#L12
I'd wrap the ul in a `nav` for semantic clarity, and then your css would be something like:

``` css
nav > ul > li {

}
```

And then you can avoid the extra class on the ul.

**Comment by adambray** [comment]
Similarly for the footer, you can probably remove the class on the `ul` and just use:

``` css
footer > ul {
}
```

and similar for your CSS.

**Comment by adambray** [comment]
Oh, I see you are already using those techniques in your CSS... thus you can just remove the extraneous classes!

**Comment by adambray** [comment]
I noticed you used negative `margin-top` on your CSS... while this isn't bad in itself, there are some edge cases where negative margin can be have unanticipated side effects. I'd suggest using a `position: relative` with a `top` declaration here, rather than a negative margin.

**Comment by adambray** [comment]
Overall... great job! :100:
