### ISSUE TITLE
James Reichard's Portfolio Page

### ISSUE THREAD

**Issue by superbuggy** [ga-wdi-exercises/portfolio_pages#67]
https://github.com/superbuggy/superbuggy.github.io

**Comment by adambray** [comment]
https://github.com/jball23/jball23.github.io/blob/60b7ce1a35e4430bdcf90cc4e391f54f3f59f315/index.html#L12
I'd encourage you to move this script to a separate JS file

**Comment by adambray** [comment]
A lot of my comments on your wendy bite submission actually apply here as well, so make sure to check those out and apply them as you see fit.

https://github.com/ga-wdi-exercises/wendy_bite/pull/51

Specifically, the stuff re: addEventListener, and setting declarations on the `*` selector.

**Comment by adambray** [comment]
Other than that, looks like you're off to a good start! :+1:
