### ISSUE TITLE
Leland's portfolio

### ISSUE THREAD

**Issue by lelandjordon** [ga-wdi-exercises/portfolio_pages#74]
Comfort: 2
Completeness: 0.25

https://github.com/lelandjordon/lelandjordon.github.io

**Comment by andrewsunglaekim** [comment]
What parts of HTML/CSS are you feeling uncomfortable with at the moment? CSS can be tricky for sure, just takes a lot of practice. And in a lot of cases(i know this is true with me at least), perseverance .

**Comment by lelandjordon** [comment]
Everything.  Right now, I don't know where to start to ask.  I went googling for info for things I thought would make sense, but I couldn't recognize any of the answers I saw.  I don't know when I'm looking at div containers or borders.  I'm going to have to start from a clean sheet.
