### ISSUE TITLE
Lab 1 - Sean

### ISSUE THREAD

**Issue by SeanTay** [ga-wdi-exercises/portfolio_pages#79]
https://github.com/SeanTay/portfolio

**Comment by SeanTay** [comment]
Comfort: 3/5
Completeness: 1/5

**Comment by SeanTay** [comment]
http://seantay.github.io/portfolio/

**Comment by RobertAKARobin** [comment]
Your code looks really good, Sean! I hardly had any comments:

https://github.com/SeanTay/portfolio/pull/1/files

If you want more specific feedback, let me know. Nice job!
