### ISSUE TITLE
Portfolio 0.1

### ISSUE THREAD

**Issue by AT89** [ga-wdi-exercises/portfolio_pages#86]
Splash/hub page validates, will revisit the portfolio page. Fixed a merge conflict from retrieving an old commit.

3/5 completeness
3/5 comfort level

https://github.com/AT89/AT89.github.io

**Comment by RobertAKARobin** [comment]
My comments:

https://github.com/AT89/AT89.github.io/pull/2

Looking good! Most of the comments are things we've already discussed.
