### ISSUE TITLE
Portfolio_pages Tyson Green

### ISSUE THREAD

**Issue by Thaisuhn** [ga-wdi-exercises/portfolio_pages#88]
Comfort level: 4.25/5
complete: 5/5

https://github.com/Thaisuhn/Thaisuhn.github.io

**Comment by jshawl** [comment]
👍 Excellent! if you use `transform:skewX` instead of `font-style:italic`, you can add a transition to the letters, like http://codepen.io/jshawl/pen/KMKJNm
