### ISSUE TITLE
Portfolio Page Courtney Seitz

### ISSUE THREAD

**Issue by Courtney-Seitz** [ga-wdi-exercises/portfolio_pages#91]
Comfort Level: 3
Completeness: 1

https://github.com/CourtneySeitz/CourtneySeitz.github.io

**Comment by RobertAKARobin** [comment]
Looking really good, Courtney! The big issues are just using proper syntax for HTML and CSS. Here are some comments:

https://github.com/CourtneySeitz/CourtneySeitz.github.io/pull/1/files

Bonus points for a great "lorem ipsum". :)
