### ISSUE TITLE
Julia Schultz portfolio page

### ISSUE THREAD

**Issue by jschultz21** [ga-wdi-exercises/portfolio_pages#92]
Repo link: https://github.com/jschultz21/jschultz21.github.io

**Question**: when I view this on the GH pages link, it seems like my non-html assets aren't being recognized...any hints as to why this would be?  When I inspect the page, the error messages read: "http://jschultz21.github.io/_css/main.css Failed to load resource: the server responded with a status of 404 (Not Found)"

Completeness: 5/5 for today, 1/5 for real life
Comfort level: 3/5

**Comment by RobertAKARobin** [comment]
Weird! I'm not sure, but I'm going to guess that it's because your folder names start with `_`. Try removing the underscores and give it another shot.

Here are my comments. Nice work! https://github.com/jschultz21/jschultz21.github.io/pull/1/files
