### ISSUE TITLE
Arthur Adams

### ISSUE THREAD

**Issue by arthuradams** [ga-wdi-exercises/portfolio_pages#96]
http://arthuradams.github.io

**Comment by arthuradams** [comment]
Much left to do. 
- Get the image placed properly (and get a proper picture of myself.)
- Put a nice box around sections.
- Experiment different fonts
- Add a nav bar, preferably vertically on the left
- Add content
  - finish resume
  - finish Who Am I?
  - finish skill inventory
  - add "What Makes Me Unique?" section

**Comment by amaseda** [comment]
Made a pull request with some code comments. Take a look. **Do not merge it!**

https://github.com/arthuradams/arthuradams.github.io/pull/1
