### ISSUE TITLE
portfolio_pages (James Hughes)

### ISSUE THREAD

**Issue by jhugheswebdev** [ga-wdi-exercises/portfolio_pages#98]
git@github.com:heezmagnif/portfolio_page.git

**Comment by jshawl** [comment]
👍 Please rename your repo to be heezmagnif.github.io so people can view it at that address.

Also, I listened to your soundlcoud - I really like the song "Carry the Weight" awesome!

**Comment by jhugheswebdev** [comment]
Thanks, man!
I'll try to do this renaming...
