### ISSUE TITLE
Michael Holzheimer HW

### ISSUE THREAD

**Issue by alpha2262** [ga-wdi-exercises/portfolio_pages#99]
Completeness: ongoing, 3ish
Correctness: 4

https://github.com/alpha2262/alpha2262.github.io

**Comment by jshawl** [comment]
👍 You're off to a great start!! I'm noticing a jump when I hover over one of the paragraphs... Consider moving the `display: inline-block` to the base `p` rule - https://github.com/alpha2262/alpha2262.github.io/blob/54370c2af999e9df07d9533d6c1cab8f848e5114/styles.css#L37

Otherwise looks great!
